version: '3.8'

services:
    mysql:
        image: mysql:8.0.32
        container_name: board-kopring-mysql
        environment:
            MYSQL_ROOT_PASSWORD: 1234
        ports:
            - "3306:3306"

    redis:
        image: redis:latest
        container_name: board-redis
        ports:
            - "6379:6379"

    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: root
            RABBITMQ_DEFAULT_PASS: root
