version: '3.8'

services:
    mysql:
        image: mysql:8.0.32
        container_name: board-kopring-mysql
        environment:
            MYSQL_ROOT_PASSWORD: 1234
        ports:
            - "3306:3306"
        networks:
            - board
    redis:
        image: redis:latest
        container_name: board-redis
        ports:
            - "6379:6379"
        networks:
            - board
    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: root
            RABBITMQ_DEFAULT_PASS: root
        networks:
            - board
    board:
        build:
            context: .
            dockerfile: Dockerfile
        image: board-kopring:latest
        depends_on:
            - mysql
            - redis
            - rabbitmq
        ports:
            - "8080:8080"
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/board
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: 1234
            SPRING_RABBITMQ_HOST: rabbitmq
            SPRING_RABBITMQ_PORT: 5672
            SPRING_RABBITMQ_USERNAME: root
            SPRING_RABBITMQ_PASSWORD: root
            SPRING_CACHE_REDIS_HOST: board-redis
            SPRING_CACHE_REDIS_PORT: 6379
        deploy:
            resources:
                limits:
                    cpus: '2'  # 원하는 CPU 제한 설정
                    memory: '1G'  # 원하는 메모리 제한 설정
        networks:
            - board
networks:
    board:
        driver: bridge
